### ISSUE TITLE
How to extract the value if it's at the bottom of question instead of right side of the question ?

### ISSUE THREAD

**Issue by jyotiyadav94** [Vishnunkumar/doc_transformers#1]

**Comment by Vishnunkumar** [comment]
Dear Jyoti,

Here, I have used a pre-trained model which was trained on FUNSD dataset where the pre-dominant data was of the form nature with the right side alignment. Hence this would have produced unsatisfactory results in your case. My suggestion would be look into huggingface website on fine-tuning for custom data of your choice and hence can broaden the spectrum to acheive better results.

**Comment by Vishnunkumar** [comment]
Closing the issue, kindly raise a new one if anything arises.
